### ISSUE TITLE
Serious problem with flickering of the values with integration with HA

### ISSUE THREAD

**Issue by michalwoz** [heishamon/HeishaMon#279]
I experienced serious issue with integration with HA on version 3.0.
I'm running default HA configuration. Tried to change heat mode and target temp. The problem is fast switching (once per second) of the value after trying to set the value. Haven't confirmed yet, but problem may occur only when value is changed fast from HA GUI. Example:

1. wanted to change target temp from 20 to 25
2. you missclicked and dropped value at 24
3. you corrected and set 25 - here the flickering begins:

There is 0 seconds or 1 second between points on X axis:
![image](https://user-images.githubusercontent.com/31922455/194492562-6be86d27-a8de-4c5f-8d17-7ef25f3949be.png)

I'm attaching console log. As we can see we receive "set z1 heat requests" HeishaMon may actually do what it is requested for. And the problem may be HA configuration.

The same situation with setting heat mode. Actually I noticed the problem with that, when I heard 1 per second relay clicking in heat pump. I consider the issue dangerous because of 2 things: exhausting HP memory write cycles limit and frequent powering on/off hp or its components.

> Fri Oct  7 08:53:34 2022 (1278532): set z1 heat request temperature to 25
Fri Oct  7 08:53:34 2022 (1278533): sent bytes: 111 including checksum value: 249 
Fri Oct  7 08:53:35 2022 (1278959): Received 203 bytes data
Fri Oct  7 08:53:35 2022 (1278960): Checksum and header received ok!
Fri Oct  7 08:53:35 2022 (1278962): received TOP7 Main_Target_Temp: 24
Fri Oct  7 08:53:35 2022 (1278967): received TOP27 Z1_Heat_Request_Temp: 24
Fri Oct  7 08:53:35 2022 (1278971): received TOP42 Z1_Water_Target_Temp: 24
Fri Oct  7 08:53:35 2022 (1279051): set z1 heat request temperature to 24
Fri Oct  7 08:53:35 2022 (1279052): sent bytes: 111 including checksum value: 250 
Fri Oct  7 08:53:35 2022 (1279558): Received 203 bytes data
Fri Oct  7 08:53:35 2022 (1279559): Checksum and header received ok!
Fri Oct  7 08:53:35 2022 (1279561): received TOP7 Main_Target_Temp: 25
Fri Oct  7 08:53:35 2022 (1279566): received TOP27 Z1_Heat_Request_Temp: 25
Fri Oct  7 08:53:35 2022 (1279570): received TOP42 Z1_Water_Target_Temp: 25
Fri Oct  7 08:53:36 2022 (1280133): set z1 heat request temperature to 25
Fri Oct  7 08:53:36 2022 (1280134): sent bytes: 111 including checksum value: 249 
Fri Oct  7 08:53:36 2022 (1280307): Requesting new 1wire temperatures
Fri Oct  7 08:53:37 2022 (1281024): Received 203 bytes data
Fri Oct  7 08:53:37 2022 (1281024): Checksum and header received ok!
Fri Oct  7 08:53:37 2022 (1281027): received TOP7 Main_Target_Temp: 24
Fri Oct  7 08:53:37 2022 (1281032): received TOP27 Z1_Heat_Request_Temp: 24
Fri Oct  7 08:53:37 2022 (1281035): received TOP42 Z1_Water_Target_Temp: 24
Fri Oct  7 08:53:37 2022 (1281040): received TOP64 High_Pressure: 10.0
Fri Oct  7 08:53:37 2022 (1281089): set z1 heat request temperature to 24
Fri Oct  7 08:53:37 2022 (1281090): sent bytes: 111 including checksum value: 250 
Fri Oct  7 08:53:37 2022 (1281555): Received 203 bytes data
Fri Oct  7 08:53:37 2022 (1281556): Checksum and header received ok!
Fri Oct  7 08:53:37 2022 (1281558): received TOP7 Main_Target_Temp: 25
Fri Oct  7 08:53:37 2022 (1281563): received TOP27 Z1_Heat_Request_Temp: 25
Fri Oct  7 08:53:37 2022 (1281567): received TOP42 Z1_Water_Target_Temp: 25
Fri Oct  7 08:53:38 2022 (1281656): set z1 heat request temperature to 25
Fri Oct  7 08:53:38 2022 (1281657): sent bytes: 111 including checksum value: 249 
Fri Oct  7 08:53:38 2022 (1282154): Received 203 bytes data
Fri Oct  7 08:53:38 2022 (1282155): Checksum and header received ok!
Fri Oct  7 08:53:38 2022 (1282157): received TOP7 Main_Target_Temp: 24
Fri Oct  7 08:53:38 2022 (1282163): received TOP27 Z1_Heat_Request_Temp: 24
Fri Oct  7 08:53:38 2022 (1282166): received TOP42 Z1_Water_Target_Temp: 24
Fri Oct  7 08:53:38 2022 (1282171): received TOP64 High_Pressure: 10.2
Fri Oct  7 08:53:38 2022 (1282226): set z1 heat request temperature to 24
Fri Oct  7 08:53:38 2022 (1282227): sent bytes: 111 including checksum value: 250 
Fri Oct  7 08:53:39 2022 (1282653): Received 203 bytes data
Fri Oct  7 08:53:39 2022 (1282654): Checksum and header received ok!
Fri Oct  7 08:53:39 2022 (1282656): received TOP7 Main_Target_Temp: 25
Fri Oct  7 08:53:39 2022 (1282661): received TOP27 Z1_Heat_Request_Temp: 25
Fri Oct  7 08:53:39 2022 (1282665): received TOP42 Z1_Water_Target_Temp: 25
Fri Oct  7 08:53:39 2022 (1282722): set z1 heat request temperature to 25
Fri Oct  7 08:53:39 2022 (1282723): sent bytes: 111 including checksum value: 249 
Fri Oct  7 08:53:39 2022 (1283153): Received 203 bytes data
Fri Oct  7 08:53:39 2022 (1283153): Checksum and header received ok!
Fri Oct  7 08:53:39 2022 (1283156): received TOP7 Main_Target_Temp: 24
Fri Oct  7 08:53:39 2022 (1283161): received TOP27 Z1_Heat_Request_Temp: 24
Fri Oct  7 08:53:39 2022 (1283164): received TOP42 Z1_Water_Target_Temp: 24
Fri Oct  7 08:53:39 2022 (1283251): set z1 heat request temperature to 24
Fri Oct  7 08:53:39 2022 (1283251): sent bytes: 111 including checksum value: 250 
Fri Oct  7 08:53:40 2022 (1283752): Received 203 bytes data
Fri Oct  7 08:53:40 2022 (1283753): Checksum and header received ok!
Fri Oct  7 08:53:40 2022 (1283755): received TOP7 Main_Target_Temp: 25
Fri Oct  7 08:53:40 2022 (1283760): received TOP27 Z1_Heat_Request_Temp: 25
Fri Oct  7 08:53:40 2022 (1283764): received TOP42 Z1_Water_Target_Temp: 25

**Comment by geduxas** [comment]
Hi, it's not related to V3.. i have same issues and from first versions.. more it is related to HA itself.. or maybe with automation rules.

**Comment by michalwoz** [comment]
@geduxas No relation to HeishaMon version is with that is what I expected. Is it possible that HeishaMon sends messages with topic `panasonic_heat_pump/commands/SetZ1HeatRequestTemperature`? Or this topic may be sent only from HA?

I don't have any automations yet.

**Comment by geduxas** [comment]
Automation scripts are in heishamon.yaml already.. 
they purpose to listen of heishamon heat shift, and change change heat shift selector in homeassistant side.. also another trigger  is watching homeassistant slide, and triggers topic to change heat shift.. and in rarely cases it will chats 2 values and starts to flickering.. personally I don't like this kind of implementation, and I have setup mqtt climate component for that.. 

 


> @geduxas No relation to HeishaMon version is with that is what I expected. Is it possible that HeishaMon sends messages with topic `panasonic_heat_pump/commands/SetZ1HeatRequestTemperature`? Or this topic may be sent only from HA?
> 
> I don't have any automations yet.

**Comment by PGnl** [comment]
@geduxas 
I am also investigating the mqqt climate component at the moment (just started) as I do not like the slider. Could you share your climate integration?

**Comment by michalwoz** [comment]
Changes made in GUI of HA with interval of ~30+ seconds seems to be OK. Maybe 15+or even 10+ seconds is also OK.

BTW my config:
![image](https://user-images.githubusercontent.com/31922455/194519637-6dd4cc0f-4140-4e79-963c-2749a740bf02.png)

**Comment by geduxas** [comment]
> @geduxas I am also investigating the mqqt climate component at the moment (just started) as I do not like the slider. Could you share your climate integration?

For now it's need to fully rewrite because of mqtt changes in HA.. i am still not done that.. if i will finish it i will post it here

**Comment by PGnl** [comment]
If you can share, I can see if I can find the time to update to the new mqqt format. 
example typically saves quite some time.
As I was planning to do so anyway, we might be able to help each other.

**Comment by geduxas** [comment]
@PGnl here is my config:

```yaml
climate:
#HeatShift
- platform: mqtt
  name: HeatPumpSetpoint
  initial: 0
  min_temp: -5
  max_temp: 5
  action_topic: "panasonic_heat_pump/main/ThreeWay_Valve_State"
  action_template: >-
    {% set values = { "0":"heating", "1":"idle" } %}
    {{ values[value] if value in values.keys() else "idle"}}
  mode_state_topic: "panasonic_heat_pump/main/Operating_Mode_State"
  mode_state_template: >-
    {% set values = { "0":"heat", "1":"cool", "2":"auto", "4":"heat", "5":"cool", "6":"auto", "7":"auto", "8":"auto" } %}
    {{ values[value] if value in values.keys() else "off"}}
  modes:
    - auto
    - heat
    - cool
    - "off"
  temperature_command_topic: "panasonic_heat_pump/commands/SetZ1HeatRequestTemperature"
  temperature_state_topic: "panasonic_heat_pump/main/Z1_Heat_Request_Temp"
  current_temperature_topic: "panasonic_heat_pump/main/Main_Outlet_Temp"
  aux_state_topic: "panasonic_heat_pump/main/Room_Heater_State"
  precision: 1.0

#DHWShift
- platform: mqtt
  name: DHWSetPoint
  initial: 50
  min_temp: 40
  max_temp: 75
  action_topic: "panasonic_heat_pump/main/ThreeWay_Valve_State"
  action_template: >-
    {% set values = { "0":"idle", "1": "heating"} %}
     {{ values[value] if value in values.keys() else "idle"}}
  mode_state_topic: "panasonic_heat_pump/main/Operating_Mode_State"
  mode_state_template: >-
    {% set values = { "3":"heat", "4":"heat", "5":"heat", "6":"heat", "8":"heat" } %}
    {{ values[value] if value in values.keys() else "off"}}
  modes:
    - heat
    - 'off'
  aux_state_topic: "panasonic_heat_pump/main/DHW_Heater_State"
  temperature_command_topic: "panasonic_heat_pump/commands/SetDHWTemp"
  temperature_state_topic: "panasonic_heat_pump/main/DHW_Target_Temp"
  current_temperature_topic: "panasonic_heat_pump/main/DHW_Temp"
  precision: 1.0
```

**Comment by PGnl** [comment]
@geduxas 

I did the heat part. Seeems to be correct and works for me. Still need to find a way to have it work for me for 2 zones. But that is for later and more for me, as I seem to be one of the few to use 2 zones. 
Believe I will eventually take out the mode selector in zone 2 and use an additional switch to adjust for zone1, zone 2 or zone 1 and 2.

What I did not get, is why you included       aux_state_topic: "panasonic_heat_pump/main/Room_Heater_State".
This topic is linked to the backup heater and also cannot be controlled via the thermostat, nor is it used.
Doen't seem to interfere with the functionality though.
Believe I would rather couple it to if the heatpump is running (Compressor frequency > 0 and no defrost).
I can also couply it to my floorheatingpump switch (if on, my logic in  node red already concluded heating is requested and Pana is working on it)

Haven't done DHW (I don't have it, but should be equal setup)
```
mqtt:
  climate:
    - name: HeatPumpSetpoint
      modes:
        - "auto"
        - "heat"
        - "cool"
        - "off"
      mode_state_topic: "panasonic_heat_pump/main/Operating_Mode_State"
      mode_state_template: >
        {% set values = { "0":"heat", "1":"cool", "2":"auto", "4":"heat", "5":"cool", "6":"auto", "7":"auto", "8":"auto" } %}
        {{ values[value] if value in values.keys() else "off"}}
      initial: 0
      min_temp: -5
      max_temp: 5
      temperature_command_topic: "panasonic_heat_pump/commands/SetZ1HeatRequestTemperature"
      temperature_state_topic: "panasonic_heat_pump/main/Z1_Heat_Request_Temp"
      current_temperature_topic: "panasonic_heat_pump/main/Z1_Temp"
      aux_state_topic: "panasonic_heat_pump/main/Room_Heater_State"
      precision: 1.0
```
For anyone using a thermostat (like me), it becomes:
```
mqtt:
  climate:
    - name: Zone 1 Panasonic
      modes:
        - "auto"
        - "heat"
        - "cool"
        - "off"
      mode_state_topic: "panasonic_heat_pump/main/Operating_Mode_State"
      mode_state_template: >
        {% set values = { "0":"heat", "1":"cool", "2":"auto", "4":"heat", "5":"cool", "6":"auto", "7":"auto", "8":"auto" } %}
        {{ values[value] if value in values.keys() else "off"}}
      initial: 18
      min_temp: 7
      max_temp: 30
      temperature_command_topic: "panasonic_heat_pump/commands/SetZ1HeatRequestTemperature"
      temperature_state_topic: "panasonic_heat_pump/main/Z1_Heat_Request_Temp"
      current_temperature_topic: "panasonic_heat_pump/main/Z1_Temp"
      aux_state_topic: "panasonic_heat_pump/main/Room_Heater_State"
      precision: 1.0
```


![image](https://user-images.githubusercontent.com/82465943/194646501-48aad953-29d1-4d38-a99c-fc09db3787ce.png)
